//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbs.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbs.Localization.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string label_apply {
            get {
                return ResourceManager.GetString("label_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string label_back {
            get {
                return ResourceManager.GetString("label_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credits.
        /// </summary>
        public static string label_credits {
            get {
                return ResourceManager.GetString("label_credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string label_language {
            get {
                return ResourceManager.GetString("label_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        public static string label_load {
            get {
                return ResourceManager.GetString("label_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string label_music {
            get {
                return ResourceManager.GetString("label_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        public static string label_newGame {
            get {
                return ResourceManager.GetString("label_newGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit.
        /// </summary>
        public static string label_quit {
            get {
                return ResourceManager.GetString("label_quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string label_resume {
            get {
                return ResourceManager.GetString("label_resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string label_save {
            get {
                return ResourceManager.GetString("label_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string label_settings {
            get {
                return ResourceManager.GetString("label_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effects.
        /// </summary>
        public static string label_sound {
            get {
                return ResourceManager.GetString("label_sound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your new hero.
        /// </summary>
        public static string menu_SelectHero {
            get {
                return ResourceManager.GetString("menu_SelectHero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start game.
        /// </summary>
        public static string menu_startGame {
            get {
                return ResourceManager.GetString("menu_startGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are dead!.
        /// </summary>
        public static string player_dead {
            get {
                return ResourceManager.GetString("player_dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new entry in your log..
        /// </summary>
        public static string system_addedQuest {
            get {
                return ResourceManager.GetString("system_addedQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to destroy this item?.
        /// </summary>
        public static string system_DestroyItem {
            get {
                return ResourceManager.GetString("system_DestroyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string system_End {
            get {
                return ResourceManager.GetString("system_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your inventory is full!.
        /// </summary>
        public static string system_InventoryFull {
            get {
                return ResourceManager.GetString("system_InventoryFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§I have the feeling that this object
        ///might be usefull at some point...
        ///I should keep it.}.
        /// </summary>
        public static string system_isQuestItem {
            get {
                return ResourceManager.GetString("system_isQuestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough Mana!.
        /// </summary>
        public static string system_notEnoughMana {
            get {
                return ResourceManager.GetString("system_notEnoughMana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough money..
        /// </summary>
        public static string system_NotEnoughMoney {
            get {
                return ResourceManager.GetString("system_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string system_off {
            get {
                return ResourceManager.GetString("system_off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string system_on {
            get {
                return ResourceManager.GetString("system_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///-.
        /// </summary>
        public static string system_questTextSeparator {
            get {
                return ResourceManager.GetString("system_questTextSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will enter: .
        /// </summary>
        public static string system_TargetLocation {
            get {
                return ResourceManager.GetString("system_TargetLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purse: .
        /// </summary>
        public static string ui_purse {
            get {
                return ResourceManager.GetString("ui_purse", resourceCulture);
            }
        }
    }
}
