//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbs.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings_questlog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_questlog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbs.Localization.strings.questlog", typeof(strings_questlog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok, killed spiders, delivered throusers.
        ///I hope I can move on now..
        /// </summary>
        public static string hollowrock_betty_01 {
            get {
                return ResourceManager.GetString("hollowrock_betty_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geddh sold the orb &quot;unwillingly&quot; to some
        ///guy in a green cape.
        ///I should have a look around here..
        /// </summary>
        public static string hollowrock_geddh_01 {
            get {
                return ResourceManager.GetString("hollowrock_geddh_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, after some troubles Jongar told me
        ///about Geddh and that he sold one of those
        ///orbs. Back to the market then....
        /// </summary>
        public static string hollowrock_jongar_01 {
            get {
                return ResourceManager.GetString("hollowrock_jongar_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serina asked me to help Geddh.
        ///Not really the adventure I was looking for....
        /// </summary>
        public static string hollowrock_merchant_01 {
            get {
                return ResourceManager.GetString("hollowrock_merchant_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I should kill some spiders in front of the town.
        ///And Serina wants some of their eyes. 
        ///What is this? A bug&apos;s life?.
        /// </summary>
        public static string hollowrock_spiders_01 {
            get {
                return ResourceManager.GetString("hollowrock_spiders_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reached Hollowrock. 
        ///A nice town actually.
        ///
        ///It has been completely rebuild after the war 
        ///against the Xesh.
        ///Lets see if I can find somone for this orb 
        ///thingy. 
        ///
        ///Or maybe I should go to the pub first...
        ///
        ///
        ///Hint: Talk to the citizens. They might say something intresting..
        /// </summary>
        public static string hollowrock_story_01 {
            get {
                return ResourceManager.GetString("hollowrock_story_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gindella, some strange old woman sent 
        ///me to some guy called Calidur to ask him 
        ///about this orb.
        ///
        ///It seems there is a lot going on in Hollowrock. 
        ///Let&apos;s see what I can do here..
        /// </summary>
        public static string hollowrock_story_02 {
            get {
                return ResourceManager.GetString("hollowrock_story_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The guard named Nisol will not let
        ///me enter the town. I will check the 
        ///surroundings. Maybe I will find 
        ///something that helps..
        /// </summary>
        public static string level_01_guard_noEntry {
            get {
                return ResourceManager.GetString("level_01_guard_noEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reached Wuran Forest.
        ///The town Hollowrock should be
        ///in the east. I am sure my first
        ///adventures await me there..
        /// </summary>
        public static string level_01_story_0 {
            get {
                return ResourceManager.GetString("level_01_story_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have found a strange stone Tablet.
        ///It says &quot;LL-WA-FA-TER&quot;.
        ///What does that mean?.
        /// </summary>
        public static string level_01_story_1 {
            get {
                return ResourceManager.GetString("level_01_story_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angus had some kind of orb. Maybe
        ///someone in Hollowrock knows more
        ///about it..
        /// </summary>
        public static string level_01_story_2 {
            get {
                return ResourceManager.GetString("level_01_story_2", resourceCulture);
            }
        }
    }
}
