//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbs.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings_hollowrock {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_hollowrock() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbs.Localization.strings.hollowrock", typeof(strings_hollowrock).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§The door is locked. And I do not think that a
        ///simple key would be enough to open it}.
        /// </summary>
        public static string abandonedHouse_01 {
            get {
                return ResourceManager.GetString("abandonedHouse_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§What the hell was that?}.
        /// </summary>
        public static string abandonedHouse_02 {
            get {
                return ResourceManager.GetString("abandonedHouse_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oh! Thank you! It only took four days to deliver....
        /// </summary>
        public static string Betty_1 {
            get {
                return ResourceManager.GetString("Betty_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want a beer? A bed? A beer in a bed? We have both!.
        /// </summary>
        public static string Betty_2 {
            get {
                return ResourceManager.GetString("Betty_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello stranger. My name is Calidur.
        ///Is this you first stay in Hollowrock? A quite nice little city!
        ///
        ///What is that? Wow! You have found one of the twelve orbs
        ///of balance! Never heard of that? 
        ///Those orbs - correctly aligned - bring balance to the world. 
        ///Unfortunately they have been stolen by Imes, the lesser god
        ///of envy. 
        ///They must be found! If you want to help us, meet mayor
        ///Jongar in his house in the south. They say he knows something..
        /// </summary>
        public static string Calidur_1 {
            get {
                return ResourceManager.GetString("Calidur_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello my friend.
        ///Do you need something? I can supply you with anything.
        ///... almost anything....
        /// </summary>
        public static string Geddh_1 {
            get {
                return ResourceManager.GetString("Geddh_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would be nice if you can help me with something...
        ///My knee has been hit by an arrow some time ago and it hurts a lot.
        ///Can you deliver this pants to Betty? She is usually at the pub..
        /// </summary>
        public static string Geddh_2 {
            get {
                return ResourceManager.GetString("Geddh_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How is you pants delivery going?.
        /// </summary>
        public static string Geddh_3 {
            get {
                return ResourceManager.GetString("Geddh_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have legendary delivery skills, I know, but we do not need
        ///to be best friends now. Do we?.
        /// </summary>
        public static string Geddh_4 {
            get {
                return ResourceManager.GetString("Geddh_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, you know about my... trade? This damn guy in his 
        ///green cape. I think his name is Olir. Some kind of wizard
        ///I would say. I did not want to sell it, but somehow I did...
        ///
        ///No idea where he is, but he still must be in Hollowrock..
        /// </summary>
        public static string Geddh_5 {
            get {
                return ResourceManager.GetString("Geddh_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello my dear.
        ///Is it your first time here in Hollowrock?
        ///In the north, there is the public district with its pub.
        ///In the south the Warriors district his famous Hall.
        ///In the east you will find the Magic and Shadow district.
        ///
        ///Oh, and about your orb? Hm... Try to speak with Calidur.
        ///He is probably somewhere at the market..
        /// </summary>
        public static string Gindella_1 {
            get {
                return ResourceManager.GetString("Gindella_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My legs hurt..
        /// </summary>
        public static string Gindella_2 {
            get {
                return ResourceManager.GetString("Gindella_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My knees hurt..
        /// </summary>
        public static string Gindella_3 {
            get {
                return ResourceManager.GetString("Gindella_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did I tell you the story of my old cat?.
        /// </summary>
        public static string Gindella_4 {
            get {
                return ResourceManager.GetString("Gindella_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My hands hurt..
        /// </summary>
        public static string Gindella_5 {
            get {
                return ResourceManager.GetString("Gindella_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where is my dog? Have you seen him?
        ///He has like... 4 legs and a tail..
        /// </summary>
        public static string Gindella_6 {
            get {
                return ResourceManager.GetString("Gindella_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am tired..
        /// </summary>
        public static string Gindella_7 {
            get {
                return ResourceManager.GetString("Gindella_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want to be a princess..
        /// </summary>
        public static string Gindella_8 {
            get {
                return ResourceManager.GetString("Gindella_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I can hear them talk. They talk about...
        ///Yes! I know whar they want. 
        ///But where is this Village of Whispers?.
        /// </summary>
        public static string Gindella_9 {
            get {
                return ResourceManager.GetString("Gindella_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This road leads to the Wuran Forest. .
        /// </summary>
        public static string hollowrock_SignPost01 {
            get {
                return ResourceManager.GetString("hollowrock_SignPost01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No littering!
        ///No begging!
        ///Dogs and cats allowed..
        /// </summary>
        public static string hollowrock_SignPost02 {
            get {
                return ResourceManager.GetString("hollowrock_SignPost02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§What does it say?} &apos;You no go over bridge!&apos;
        ///${§There is no bridge. And who writes like this?}.
        /// </summary>
        public static string hollowrock_SignPost03 {
            get {
                return ResourceManager.GetString("hollowrock_SignPost03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have reached Hollowrock. A nice town actually.
        ///
        ///It has been completely rebuild after the war against the Xesh.
        ///
        ///Lets see if I can find somone for this orb thingy. 
        ///
        ///Or maybe I should go to the pub first...
        ///
        ///
        ///Hint: Talk to the citizens. They might say something intresting..
        /// </summary>
        public static string hollowrock_story_01 {
            get {
                return ResourceManager.GetString("hollowrock_story_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I do not wanna talk right now!.
        /// </summary>
        public static string Jongar_1 {
            get {
                return ResourceManager.GetString("Jongar_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calidur sent you, right? This crazy old man.
        ///With his stupid magic balls. We have more important 
        ///things to do! 
        ///But ok, you helped us, so I will help you... IF you can 
        ///solve this riddle:
        ///I only exist when light is present, yet light on me is my 
        ///immediate death. What am I?.
        /// </summary>
        public static string Jongar_2 {
            get {
                return ResourceManager.GetString("Jongar_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That is correct my friend!
        ///Well, listen. Geddh, the trader on the market sold some
        ///kind of orb ... or however you call it. He seems to be quite
        ///upset about it. That is all I can tell..
        /// </summary>
        public static string Jongar_3 {
            get {
                return ResourceManager.GetString("Jongar_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have work to do now..
        /// </summary>
        public static string Jongar_4 {
            get {
                return ResourceManager.GetString("Jongar_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello stranger, my husband Jongar is in a bad mood because of the
        ///spiders infront of the town. Nobody wants to deal with them. Not even 
        ///the guards. Maybe you can helo us? And if you&apos;re already there, mind bring
        ///me 6 spider eyes? I need them for ... things.....
        /// </summary>
        public static string Serina_1 {
            get {
                return ResourceManager.GetString("Serina_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for the eyes! 
        ///Can I ask you for one more thing? Geddh, the merchant, needs some
        ///goods to be delivered. Would you be so kind to help him? I would do
        ///it myself but I have things to do....
        /// </summary>
        public static string Serina_2 {
            get {
                return ResourceManager.GetString("Serina_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hm... are you done with the spiders yet?.
        /// </summary>
        public static string Serina_3 {
            get {
                return ResourceManager.GetString("Serina_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you help Geddh already?.
        /// </summary>
        public static string Serina_4 {
            get {
                return ResourceManager.GetString("Serina_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your help. I could convince Jongar to talk
        ///with you..
        /// </summary>
        public static string Serina_5 {
            get {
                return ResourceManager.GetString("Serina_5", resourceCulture);
            }
        }
    }
}
