//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Orbs.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class strings_wuranforest {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings_wuranforest() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Orbs.Localization.strings.wuranforest", typeof(strings_wuranforest).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§Three eyes? Why does this spider have only three?}.
        /// </summary>
        public static string eyePickup {
            get {
                return ResourceManager.GetString("eyePickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are you? What do you want?
        ///Meh... I don&apos;t care. Go away or I will cut you!.
        /// </summary>
        public static string level01_AngusNeutral {
            get {
                return ResourceManager.GetString("level01_AngusNeutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where do you have this from? Where is Fosco?
        ///That&apos;s it! You are going to die now!.
        /// </summary>
        public static string level01_AngusTriggered {
            get {
                return ResourceManager.GetString("level01_AngusTriggered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey Fosco,
        ///I got rid of the others. Now we can share the money fifty - fifty.
        ///And I have found some strange glowing sphere.
        ///Hurry up, meet me at the camp in the south.
        ///-Angus
        ///
        ///${§I am not Fosco, but what does it matter.
        ///Maybe I can trick Angus somehow?
        ///And what sphere is he talking about?}.
        /// </summary>
        public static string level01_BushNote_01 {
            get {
                return ResourceManager.GetString("level01_BushNote_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard Nisol,
        ///I already told you that you can enter the town.
        ///Just go..
        /// </summary>
        public static string level01_Guard_01 {
            get {
                return ResourceManager.GetString("level01_Guard_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard Nisol,
        ///Hm, some extra money would be nice.
        ///Maybe you are not that bad.
        ///You now can enter the town, but behave!.
        /// </summary>
        public static string level01_Guard_02 {
            get {
                return ResourceManager.GetString("level01_Guard_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guard Nisol,
        ///Weird people are wandering around. Strangers are not allowed 
        ///to enter the town any more.
        ///Sorry, move along..
        /// </summary>
        public static string level01_Guard_03 {
            get {
                return ResourceManager.GetString("level01_Guard_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a jar.
        ///One is enough..
        /// </summary>
        public static string level01_Jar_01 {
            get {
                return ResourceManager.GetString("level01_Jar_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have picked up an emtpy jar..
        /// </summary>
        public static string level01_Jar_02 {
            get {
                return ResourceManager.GetString("level01_Jar_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your jar is already full..
        /// </summary>
        public static string level01_Jar_03 {
            get {
                return ResourceManager.GetString("level01_Jar_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have filled your emtpy jar with water..
        /// </summary>
        public static string level01_Jar_04 {
            get {
                return ResourceManager.GetString("level01_Jar_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have no container for the water..
        /// </summary>
        public static string level01_Jar_05 {
            get {
                return ResourceManager.GetString("level01_Jar_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not need another jar..
        /// </summary>
        public static string level01_Jar_06 {
            get {
                return ResourceManager.GetString("level01_Jar_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello fellows,
        ///Good that you have found the stone, told you It will work.
        ///I have found a way to get inside the town.
        ///We must keep this to our self!
        ///The guard at the entrance can be bought.
        ///Your cut of the last robbery is hidden nearby.
        ///That should be enough to get inside.
        ///Two arrows under a light will show you the way.
        ///See you soon
        ///-Angus.
        /// </summary>
        public static string level01_Note_01 {
            get {
                return ResourceManager.GetString("level01_Note_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§A red bush.
        ///Nothing to do here I think.}.
        /// </summary>
        public static string level01_RedBush_01 {
            get {
                return ResourceManager.GetString("level01_RedBush_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right next to the water, but still looks dry..
        /// </summary>
        public static string level01_RedBush_02 {
            get {
                return ResourceManager.GetString("level01_RedBush_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This path leads to Hollowrock.
        ///${§I probably should go there.}.
        /// </summary>
        public static string level01_SignPost01_01 {
            get {
                return ResourceManager.GetString("level01_SignPost01_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red, round and bushy, I am sitting by the water.
        ///Make me wet and I may give you a quarter.
        ///
        ///${§How to make something wet?
        ///Wasn&apos;t there a bunch of blue jars
        ///by the well a bit north of the road?}.
        /// </summary>
        public static string level01_SignPost01_02 {
            get {
                return ResourceManager.GetString("level01_SignPost01_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§This leads to some dark cave.
        ///Smells quite bad.
        ///Better not go inside.}.
        /// </summary>
        public static string level01_SignPostCave {
            get {
                return ResourceManager.GetString("level01_SignPostCave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grendelins&apos; field!
        ///Keep out!
        ///
        ///${§Because of all the vegetables?
        ///Doubtfull.}.
        /// </summary>
        public static string level01_SignPostField {
            get {
                return ResourceManager.GetString("level01_SignPostField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;Hollowrock Pond&apos;
        ///
        ///${§Definetly too cold for a bath.}.
        /// </summary>
        public static string level01_SignPostLake {
            get {
                return ResourceManager.GetString("level01_SignPostLake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§I have found a strange stone tablet.
        ///There are letters encraved. They say:
        ///LL-WA-FA-TER
        ///What does that mean?}.
        /// </summary>
        public static string level01_StoneTablet {
            get {
                return ResourceManager.GetString("level01_StoneTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So, this is where it starts. In the summer of 262 o.U.
        ///
        ///It was about time to leave Urgads house an stand on my own feet.
        ///
        ///Toria is a big country, I am curios what challanges await me.
        ///
        ///Allthough... The Wuran Forest is famous for it&apos;s ... boredom...
        ///
        ///Maybe I should head east to Hollowrock.
        ///
        ///
        ///
        ///Hint:
        ///Many objects in the world are interactable. Click them..
        /// </summary>
        public static string level01_Story_01 {
            get {
                return ResourceManager.GetString("level01_Story_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ${§Angus had this orb with him.
        ///What am I supposed to do with it?
        ///Maybe someone in Hollowrock knows.}.
        /// </summary>
        public static string orbPickUp {
            get {
                return ResourceManager.GetString("orbPickUp", resourceCulture);
            }
        }
    }
}
